# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: ocala
    main: ./cmd/ocala
    binary: bin/ocala
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -X main.version={{.Version}}
  - id: ocala-language-server
    dir: language-server
    main: .
    binary: bin/ocala-language-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE.txt
      - NOTICE.txt
      - README.md
      - share/ocala/include/mos6502.oc
      - share/ocala/include/msx.oc
      - share/ocala/include/msx/romram.oc
      - share/ocala/include/noarch.oc
      - share/ocala/include/z80.oc
      - share/ocala/misc/ocala-mode.el
    wrap_in_directory: "{{ .ProjectName }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
